title: Snipcart
baseURL: /
params:
  logos:
    dark:
      fallback: images/logo.svg
      optimized: images/logo.svg
    light:
      fallback: images/logo-white.svg
      optimized: images/logo-white.svg
  palette: default
  palettes:
    default:
      sass:
        active: '#88DD9B'
        active_dark: '#547567'
        active_light: '#C0FDB6'
        active_medium: '#5C9174'
        bg_image_cart_fallback: /images/header.jpg
        bg_image_cart_optimized: /images/cart-bg.webp
        bg_image_primary_fallback: /images/header.jpg
        bg_image_primary_optimized: /images/header.webp
        bg_image_product_fallback: /images/leaf.svg
        bg_image_product_optimized: /images/leaf.svg
        bg_image_secondary_fallback: /images/leaf-light-grey.svg
        bg_image_secondary_optimized: /images/leaf-light-grey.svg
        dark: '#384647'
        dark_grey: '#273132'
        default: '#FFFFFF'
        light: '#F0F0F0'
        light_grey: '#6B797A'
        medium: '#6B797A'
  snipcart_api_key: Y2VlNWZkNzgtNTgzYy00Nzg2LWFkZjEtMDNmM2JmZDg2MDc2NjM3MDc1NDEyNjUxMTIzMTIy
  snipcart_css: 'https://cdn.snipcart.com/themes/v3.0.0/default/snipcart.css'
  snipcart_js: 'https://cdn.snipcart.com/themes/v3.0.0/default/snipcart.js'
disableKinds:
  - RSS
